import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LeftNav from "../components/LeftNav";
import RightInspector from "../components/RightInspector";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "216px minmax(0,1fr) 352px",
            minHeight: "100vh",
            background: "var(--color-bg)",
            color: "var(--color-text)",
            fontFamily: "var(--font-body)",
          }}
        >
          <LeftNav />
          <main
            style={{
              minWidth: 0,
              padding: "var(--space-6) var(--space-6) var(--space-8)",
              display: "flex",
              flexDirection: "column",
              gap: "var(--space-6)",
            }}
          >
            {children}
          </main>
          <RightInspector />
        </div>
      </body>
    </html>
  );
}
